// Binding: Gắn giá trị trong html với biến trong js
// Ví dụ: trong html: phần tử input.value, trong js: biến quantity: đồng bộ

// Vanila JS (không dùng framework, js thuần): Không có binding => Binding thủ công 2 chiều
// ReactJs: Có binding 1 chiều: state => UI   (quantity => input.value) => Thủ công input.value -> quantity
// VueJs: Có binding 2 chiều: state <=> UI   (quantity <=> input.value)